spring:
  datasource:
    username: root
    password: 1005
    url: jdbc:mysql://localhost:3306/tylg2020?useUnicode=true&serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #Spring Boot 默认是不注入这些属性值的，需要自己绑定
    #druid 数据源专有配置
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙，stat用于监控统计
      filters: stat,wall,slf4j
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      stat-view-servlet:
        allow:
        deny:
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
        reset-enable: false
      web-stat-filter:
        exclusions: "*.js,*.gif,*.png,*.jpg,*.css,*.ico,/druid/*"
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
    publisher-confirms: true #是否确认回调
    publisher-returns: true #是否返回回调
    listener:
      simple:
        acknowledge-mode: manual #采用手动答应
        concurrency: 1 #指定最小消费者数量
        max-concurrency: 3 #指定最大消费者数量
        retry:
          enabled: true #是否支持重试
    virtual-host: /

mybatis:
  type-aliases-package: com.hello.dal.config.dataobject
  mapper-locations: classpath:com/hello/dal/config/mapper/config/*.xml

logging:
  config: classpath:logback-spring.xml
  level:
    com:
      hello:
        dal:
          config:
            mapper: debug



